### ISSUE TITLE
Commas within the descriptions are interpreted as separators.

### ISSUE THREAD

**Issue by myclark** [nluetzge/LISA_acronyms_dictionary#2]
This is likely expected behaviour for a csv file, since, you know, "comma separated values". However, in this case there are only three columns so the subsequent commas after the first two can be safely ignored (at least for now).

Do putting descriptions inside quotes fix this?

**Comment by nluetzge** [comment]
Argh yes that happens and yes putting things into quotes is the fix. I usually edit the table in programs that do that autmatically.

**Comment by myclark** [comment]
I suspect there is a way to fix this with an alteration of the CSV read function, maybe the format parameter and something something regex... I may get nerdsniped enough to have a look later...

**Comment by nluetzge** [comment]
Well if we go this way we need something that works in Pyhton and JavaScript as well since this table is used for both, the GUI and the webtool.

**Comment by myclark** [comment]
Ahhhh, that explains why it works on the web but not in the python GUI, I was getting errors due to the uneven headers and data columns and was wondering why it was still working on the web. Ok, then that is a good reason to fix the CSV file itself.

**Comment by nluetzge** [comment]
Yes! Oh I should have tested the gui before merging 😬 It is alwo often giving me some problems with the encoding of the csv file. And with "It" I mean python.
