### ISSUE TITLE
GPRM description

### ISSUE THREAD

**Issue by lemiere** [nluetzge/LISA_acronyms_dictionary#3]
Hi,

Progbably the GPRM description is not the right one...
Here a copy past about the GPRM request :+1: 
------
Grabbing Position Release Mechanism
DESCRIPTION

[IDS doc] Each OB has two Fibre-Switch-Units (FSUs), one to provide the means to switch between the prime and redundant OB feed fibres (coming from the laser system) and one to switch between the prime and redundant backlink fibre.
-----

My best

**Comment by nluetzge** [comment]
Weird looks like it got the description of the FSU...

**Comment by lemiere** [comment]
nor for : 
GTO,Geostationary Transfer Orbit,"refers to variation of TTL between what was measured on ground during AIVT, and wht we end up with in space - [my wording of my I got from Ewan@LIG PM3]"

**Comment by lemiere** [comment]
probably from : LISA_acronyms_study_team.csv

**Comment by nluetzge** [comment]
I blame the study team. I just checked where those are coming from and they come from the table of the study team.. I will try to fix them.
