### ISSUE TITLE
Missing acronyms

### ISSUE THREAD

**Issue by nluetzge** [nluetzge/LISA_acronyms_dictionary#4]
Just collecting some here:
OBMCU=??

**Comment by rjrosati** [comment]
Here are some more:

- USR: ultra slow-roll inflation model (common mechanism in primordial black hole production models)
- SIGW: scalar-induced gravitational waves (stochastic backgrounds formed by the collapse of overdensities in the primordial powerspectrum)
- PT: phase transition (like FOPT)
- GWB: gravitational wave background (as in SGWB)
- STFT: short-time Fourier transform (used in some LISA data analysis pipelines)
- FFT: fast fourier transform
- LFN: laser frequency noise
- LCDM / ΛCDM

**Comment by nluetzge** [comment]
Thanks! Will let you know when they are added. Sorry for the delay.

**Comment by nluetzge** [comment]
STS - IDS stable structure
POAD - Performance Operations Assumptions Document
